# Generated by Django 2.1.7 on 2019-02-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg_send_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('captcha', models.CharField(max_length=6)),
                ('msg_code', models.CharField(max_length=6)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('verify_times', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'msg_send_log',
            },
        ),
    ]
