# Generated by Django 2.1.7 on 2019-02-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_msg_send_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg_send_log',
            name='captcha',
        ),
    ]
