# Generated by Django 2.1.7 on 2019-03-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cate_name',
            field=models.CharField(max_length=20),
        ),
    ]
